package exceptions;

public class WithFinally
{
	public int getNumber()
	{
		int i = 25;
		try
		{
			
		}
		catch(Exception e)
	}
	public static void main(String[] args)
	{
		// TODO Auto-generated method stub
	}
}
